### PR TITLE
Pbi 8 location

### PR DESCRIPTION
**Pull request by sagabs**
Please review brother and sister, in my device work well

### CODE REVIEW

**Comment by sagabs** [comment]
merge PBI 8 lokasi to staging

**Review by cindysurjawann — APPROVED** [review]
working well in my local too

**Review by calvinyonathan — APPROVED** [review]
Tidak ada masalah silahkan di merge

**Review by Fatur525 — APPROVED** [review]
Tadi sudah manual testing secara langsung, alhamdulillah bisa

**Pull request closed without merging**
