### PR TITLE
Coldfix

### PR DESCRIPTION
**Pull request by sagabs**
implementing TDD

### CODE REVIEW

**Comment by sagabs** [comment]
implementing TDD able to merge

**Review by cindysurjawann — APPROVED** [review]
issue testing sudah fix

**Review by calvinyonathan — APPROVED** [review]
Oke Approve , Boleh di Merge

**Review by Fatur525 — APPROVED** [review]
Mantap, tapi kurang testing

**Review by diwaandrew — APPROVED** [review]
Clean Code

**Pull request merged**
